// ABOUTME: Mahaclinic service worker. Cache-first under /mahaclinic/*.
// ABOUTME: Generated by scripts/build_mahaclinic_sw.py — do not hand-edit.

const CACHE = "mahaclinic-v1.0.0";

const ASSETS = [
  "/mahaclinic/",
  "/mahaclinic/index.html",
  "/mahaclinic/drug.html",
  "/mahaclinic/about/",
  "/mahaclinic/about/index.html",
  "/mahaclinic/app.js",
  "/mahaclinic/styles.css",
  "/mahaclinic/manifest.json",
  "/mahaclinic/icons/icon-192.png",
  "/mahaclinic/icons/icon-512.png",
  "/mahaclinic/icons/apple-touch-icon.png",
  "/mahaclinic/data/_index.json",
  "/mahaclinic/data/_config.json",
  "/theme/css/book-tokens.css",
  "/mahaclinic/data/adbry-ad-adult.json",
  "/mahaclinic/adbry-ad-adult/",
  "/mahaclinic/adbry-ad-adult/index.html",
  "/mahaclinic/data/adbry-ad-peds.json",
  "/mahaclinic/adbry-ad-peds/",
  "/mahaclinic/adbry-ad-peds/index.html",
  "/mahaclinic/data/bimzelx-hs.json",
  "/mahaclinic/bimzelx-hs/",
  "/mahaclinic/bimzelx-hs/index.html",
  "/mahaclinic/data/bimzelx-pso.json",
  "/mahaclinic/bimzelx-pso/",
  "/mahaclinic/bimzelx-pso/index.html",
  "/mahaclinic/data/cibinqo-ad.json",
  "/mahaclinic/cibinqo-ad/",
  "/mahaclinic/cibinqo-ad/index.html",
  "/mahaclinic/data/cosentyx-hs.json",
  "/mahaclinic/cosentyx-hs/",
  "/mahaclinic/cosentyx-hs/index.html",
  "/mahaclinic/data/cosentyx-pso.json",
  "/mahaclinic/cosentyx-pso/",
  "/mahaclinic/cosentyx-pso/index.html",
  "/mahaclinic/data/dupixent-ad.json",
  "/mahaclinic/dupixent-ad/",
  "/mahaclinic/dupixent-ad/index.html",
  "/mahaclinic/data/dupixent-bp.json",
  "/mahaclinic/dupixent-bp/",
  "/mahaclinic/dupixent-bp/index.html",
  "/mahaclinic/data/dupixent-pn.json",
  "/mahaclinic/dupixent-pn/",
  "/mahaclinic/dupixent-pn/index.html",
  "/mahaclinic/data/dupixent-urticaria.json",
  "/mahaclinic/dupixent-urticaria/",
  "/mahaclinic/dupixent-urticaria/index.html",
  "/mahaclinic/data/ebglyss-ad.json",
  "/mahaclinic/ebglyss-ad/",
  "/mahaclinic/ebglyss-ad/index.html",
  "/mahaclinic/data/humira-hs.json",
  "/mahaclinic/humira-hs/",
  "/mahaclinic/humira-hs/index.html",
  "/mahaclinic/data/humira-pso.json",
  "/mahaclinic/humira-pso/",
  "/mahaclinic/humira-pso/index.html",
  "/mahaclinic/data/icotyde-pso.json",
  "/mahaclinic/icotyde-pso/",
  "/mahaclinic/icotyde-pso/index.html",
  "/mahaclinic/data/leqselvi-aa.json",
  "/mahaclinic/leqselvi-aa/",
  "/mahaclinic/leqselvi-aa/index.html",
  "/mahaclinic/data/litfulo-aa.json",
  "/mahaclinic/litfulo-aa/",
  "/mahaclinic/litfulo-aa/index.html",
  "/mahaclinic/data/nemluvio-ad.json",
  "/mahaclinic/nemluvio-ad/",
  "/mahaclinic/nemluvio-ad/index.html",
  "/mahaclinic/data/nemluvio-pn.json",
  "/mahaclinic/nemluvio-pn/",
  "/mahaclinic/nemluvio-pn/index.html",
  "/mahaclinic/data/olumiant-aa.json",
  "/mahaclinic/olumiant-aa/",
  "/mahaclinic/olumiant-aa/index.html",
  "/mahaclinic/data/otezla-pso.json",
  "/mahaclinic/otezla-pso/",
  "/mahaclinic/otezla-pso/index.html",
  "/mahaclinic/data/rhapsido-urticaria.json",
  "/mahaclinic/rhapsido-urticaria/",
  "/mahaclinic/rhapsido-urticaria/index.html",
  "/mahaclinic/data/rinvoq-ad.json",
  "/mahaclinic/rinvoq-ad/",
  "/mahaclinic/rinvoq-ad/index.html",
  "/mahaclinic/data/skyrizi-pso.json",
  "/mahaclinic/skyrizi-pso/",
  "/mahaclinic/skyrizi-pso/index.html",
  "/mahaclinic/data/sotyktu-pso.json",
  "/mahaclinic/sotyktu-pso/",
  "/mahaclinic/sotyktu-pso/index.html",
  "/mahaclinic/data/taltz-pso-adult.json",
  "/mahaclinic/taltz-pso-adult/",
  "/mahaclinic/taltz-pso-adult/index.html",
  "/mahaclinic/data/taltz-pso-peds.json",
  "/mahaclinic/taltz-pso-peds/",
  "/mahaclinic/taltz-pso-peds/index.html",
  "/mahaclinic/data/tremfya-pso.json",
  "/mahaclinic/tremfya-pso/",
  "/mahaclinic/tremfya-pso/index.html"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k.startsWith("mahaclinic-") && k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (!url.pathname.startsWith("/mahaclinic/")) return;
  event.respondWith(
    caches.match(event.request).then(cached => {
      if (cached) return cached;
      return fetch(event.request).then(resp => {
        if (!resp.ok) return resp;
        const clone = resp.clone();
        caches.open(CACHE).then(c => c.put(event.request, clone));
        return resp;
      }).catch(() => cached || new Response("Offline", { status: 503 }));
    })
  );
});
