"""ABOUTME: Generates mahaclinic sw.js with a precache list derived from _index.json.
ABOUTME: Run after extraction + index build. Cache name includes the config version."""

import json
import pathlib

ROOT = pathlib.Path("content/extra/mahaclinic")
INDEX = ROOT / "data/_index.json"
CONFIG = ROOT / "data/_config.json"

entries = json.loads(INDEX.read_text())
config = json.loads(CONFIG.read_text())
slugs = [e["slug"] for e in entries]

precache_list = [
    "/mahaclinic/",
    "/mahaclinic/index.html",
    "/mahaclinic/drug.html",
    "/mahaclinic/about/",
    "/mahaclinic/about/index.html",
    "/mahaclinic/app.js",
    "/mahaclinic/styles.css",
    "/mahaclinic/manifest.json",
    "/mahaclinic/icons/icon-192.png",
    "/mahaclinic/icons/icon-512.png",
    "/mahaclinic/icons/apple-touch-icon.png",
    "/mahaclinic/data/_index.json",
    "/mahaclinic/data/_config.json",
    "/theme/css/book-tokens.css",
]
for slug in slugs:
    precache_list.append(f"/mahaclinic/data/{slug}.json")
    precache_list.append(f"/mahaclinic/{slug}/")
    precache_list.append(f"/mahaclinic/{slug}/index.html")

sw_content = f"""\
// ABOUTME: Mahaclinic service worker. Cache-first under /mahaclinic/*.
// ABOUTME: Generated by scripts/build_mahaclinic_sw.py — do not hand-edit.

const CACHE = "mahaclinic-v{config['version']}";

const ASSETS = {json.dumps(precache_list, indent=2)};

self.addEventListener("install", (event) => {{
  event.waitUntil(
    caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())
  );
}});

self.addEventListener("activate", (event) => {{
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k.startsWith("mahaclinic-") && k !== CACHE).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
}});

self.addEventListener("fetch", (event) => {{
  const url = new URL(event.request.url);
  if (!url.pathname.startsWith("/mahaclinic/")) return;
  event.respondWith(
    caches.match(event.request).then(cached => {{
      if (cached) return cached;
      return fetch(event.request).then(resp => {{
        if (!resp.ok) return resp;
        const clone = resp.clone();
        caches.open(CACHE).then(c => c.put(event.request, clone));
        return resp;
      }}).catch(() => cached || new Response("Offline", {{ status: 503 }}));
    }})
  );
}});
"""

(ROOT / "sw.js").write_text(sw_content)
print(f"Wrote sw.js with {len(precache_list)} assets, cache name mahaclinic-v{config['version']}")
